# Generated by Django 5.2.6 on 2025-09-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('que_hizo_ayer', models.TextField()),
                ('que_hara_hoy', models.TextField()),
                ('impedimentos', models.TextField(blank=True, null=True)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backlog.integrante')),
            ],
            options={
                'unique_together': {('integrante', 'fecha')},
            },
        ),
    ]
