# Generated by Django 5.2.6 on 2025-09-24 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_daily'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daily',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='daily',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='daily',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
