# Generated by Django 5.2.6 on 2025-09-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0003_alter_daily_unique_together_daily_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='criterios_aceptacion',
            field=models.TextField(blank=True, help_text='Criterios que deben cumplirse para cerrar esta tarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='informe_cierre',
            field=models.FileField(blank=True, help_text='Archivo requerido para cerrar la tarea', null=True, upload_to='informes_cierre/'),
        ),
    ]
