# Generated by Django 5.2.6 on 2025-09-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0005_remove_evidencia_fecha_evidencia_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='fuera_horario',
            field=models.BooleanField(default=False),
        ),
    ]
