# Generated by Django 5.2.6 on 2025-09-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0006_daily_fuera_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='nombre',
            field=models.CharField(default='Sprint', max_length=50),
        ),
    ]
