# Generated by Django 5.2.6 on 2025-09-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0007_sprint_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('APROBADO', 'Aprobado'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('BLOQUEADO', 'Bloqueado')], default='NUEVO', help_text='Estado actual de la tarea en el workflow', max_length=20),
        ),
    ]
