# Generated by Django 5.2.6 on 2025-10-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0009_epica'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='epica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='backlog.epica'),
        ),
    ]
