# Generated by Django 5.2.6 on 2025-10-28 17:12

import backlog.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0010_tarea_epica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador corto (ej. NEUCONTA, CPS, JURIDICO).', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='epica',
            options={'ordering': ['-creada_en']},
        ),
        migrations.RemoveField(
            model_name='epica',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='epica',
            name='nombre',
        ),
        migrations.AddField(
            model_name='epica',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='avance_manual',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0–100. Si se deja vacío, se calcula por tareas.', null=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código legible (ej. NEUSI-001).', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='documentos_url',
            field=models.URLField(blank=True, help_text='Enlace a carpeta o documento maestro'),
        ),
        migrations.AddField(
            model_name='epica',
            name='estado',
            field=models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('ACTIVA', 'Activa'), ('EN_PAUSA', 'En pausa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20),
        ),
        migrations.AddField(
            model_name='epica',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='kpis',
            field=models.TextField(blank=True, help_text='Métricas clave esperadas para la épica'),
        ),
        migrations.AddField(
            model_name='epica',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Responsables/co-owners de la épica', related_name='epicas_cocreadas', to='backlog.integrante'),
        ),
        migrations.AddField(
            model_name='epica',
            name='sprints',
            field=models.ManyToManyField(blank=True, related_name='epicas', to='backlog.sprint'),
        ),
        migrations.AddField(
            model_name='epica',
            name='titulo',
            field=models.CharField(default='Epica migrada', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='asignados',
            field=models.ManyToManyField(blank=True, related_name='tareas_asignadas', to='backlog.integrante'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='esfuerzo_sp',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Story points (1, 2, 3, 5, 8, 13, 21)', null=True, validators=[backlog.models.validar_story_points]),
        ),
        migrations.AlterField(
            model_name='epica',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epicas_propias', to='backlog.integrante'),
        ),
        migrations.AlterField(
            model_name='epica',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='rol',
            field=models.CharField(choices=[('Scrum Master / PO', 'Scrum Master / PO'), ('Arquitecto de Software y Director General', 'Arquitecto de Software y Director General'), ('Coordinadora de Gestión Humana y Administrativa', 'Coordinadora de Gestión Humana y Administrativa'), ('Visualizador', 'Visualizador'), ('Product Owner', 'Product Owner'), ('Product Owner Coofisam360', 'Product Owner Coofisam360'), ('Administrador de Bases de Datos (DBA)', 'Administrador de Bases de Datos (DBA)'), ('Líder Comercial', 'Líder Comercial'), ('Especialista en Visualización y BI', 'Especialista en Visualización y BI'), ('Desarrollador Frontend', 'Desarrollador Frontend'), ('Desarrollador Backend', 'Desarrollador Backend'), ('Coordinadora de Marketing y Comunicación', 'Coordinadora de Marketing y Comunicación'), ('Contadora General', 'Contadora General'), ('Miembro', 'Miembro')], default='Miembro', max_length=100),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas_legacy', to='backlog.integrante'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='criterios_aceptacion',
            field=models.TextField(blank=True, help_text='Criterios para cerrar la tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('APROBADO', 'Aprobado'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('BLOQUEADO', 'Bloqueado')], default='NUEVO', help_text='Estado actual en el workflow', max_length=20),
        ),
        migrations.AddField(
            model_name='epica',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta épica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epicas', to='backlog.proyecto'),
        ),
        migrations.CreateModel(
            name='PermisoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_proyectos', to='backlog.integrante')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_integrantes', to='backlog.proyecto')),
            ],
            options={
                'unique_together': {('integrante', 'proyecto')},
            },
        ),
    ]
