# Generated by Django 5.2.6 on 2025-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0011_proyecto_alter_epica_options_remove_epica_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epica',
            name='nombre',
            field=models.CharField(blank=True, db_index=True, help_text="Alias de 'titulo' para compatibilidad con la API.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('BLOQUEADO', 'Bloqueado')], default='NUEVO', help_text='Estado actual en el workflow', max_length=20),
        ),
    ]
