# Generated by Django 5.2.6 on 2025-09-25 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(help_text='Fecha de inicio de la semana (lunes)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad Semanal',
                'verbose_name_plural': 'Disponibilidades Semanales',
                'ordering': ['-semana_inicio'],
                'unique_together': {('usuario', 'semana_inicio')},
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Mi??rcoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'S??bado'), (6, 'Domingo')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('hora', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('parcial', 'Parcialmente Disponible')], default='ocupado', max_length=20)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('disponibilidad_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='disponibilidad.disponibilidadsemanal')),
            ],
            options={
                'ordering': ['dia_semana', 'hora'],
                'unique_together': {('disponibilidad_semanal', 'dia_semana', 'hora')},
            },
        ),
    ]
